spring:
  mvc:
    charset: UTF-8
    enabled: true
    force: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: TmallMarket
  datasource:
    username: root
    password: 412824wyl
    url: jdbc:mysql://localhost:3306/sys?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html