spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: TmallMarket
  datasource:
    druid:
      username: root
      password: 412824wyl
      url: jdbc:mysql://localhost:3306/sys?useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
